services:
  registry:
    image: registry:2
    restart: unless-stopped
    volumes:
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_HTTP_SECRET: ${SERVICE_BASE64_REGISTRY}

  openclaw:
    image: ghcr.io/openclaw/openclaw:latest # Changed from build to image
    restart: on-failure:10
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      DOCKER_HOST: tcp://docker-proxy:2375
      OPENCLAW_ENABLE_WEBHOOK_PROXY: "1"
      PORT: 18789
      NODE_ENV: production
      OPENCLAW_GATEWAY_PORT: 18789
      OPENCLAW_STATE_DIR: /data/.openclaw
      OPENCLAW_WORKSPACE: /data/openclaw-workspace
      # Ensure these are defined in the Environment Variables tab:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      SERVICE_FQDN_OPENCLAW: ${SERVICE_FQDN_OPENCLAW}
    volumes:
      - openclaw-data:/data
      - openclaw-config:/root/.openclaw
      - openclaw-workspace:/root/openclaw-workspace
    depends_on:
      - docker-proxy
    command: ["bash", "/app/scripts/bootstrap.sh"]

  docker-proxy:
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      POST: 1
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      INFO: 1
      VERSION: 1
      EXEC: 1

  searxng:
    image: searxng/searxng:latest # Changed from build to image
    restart: unless-stopped
    volumes:
      - searxng-data:/var/lib/searxng
    environment:
      SEARXNG_BASE_URL: http://searxng:8080
      SEARXNG_SERVER_SECRET_KEY: ${SERVICE_BASE64_SEARXNG}

volumes:
  openclaw-data:
  openclaw-config:
  openclaw-workspace:
  searxng-data:
  registry-data:
